spin_manifest_version = 2

[application]
name = "aos-chal-one"
version = "0.1.0"
authors = ["Dimitri <5898931+dimitrilw@users.noreply.github.com>"]
description = "Fermyon advent-of-spin 2023, challenge 1"

# --------------------------------------------------------------------------------------------------
# main component, performing CRUD operations

[[trigger.http]]
route = "/data"
component = "aos-chal-one"

[component.aos-chal-one]
source = "target/wasm32-wasi/release/aos_chal_one.wasm"
allowed_outbound_hosts = []
[component.aos-chal-one.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]

# --------------------------------------------------------------------------------------------------
# fs component serving static asset `index.html`

[[trigger.http]]
route = "/index.html"
component = "fs"

[component.fs]
files = [{ source = "static/index.html", destination = "/index.html" }]

[component.fs.source]
url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm"
digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4"
